import React from 'react'
import Head from 'next/head'
import Navbar from './Navbar'
import Script from 'next/script'
import Konten from './Konten'

// import { useRouter } from "next/router";

export default function BaseLayouts(props) {
  return (
    <div className="first:w-full min-h-screen bg-white flex flex-row">
      <Head>
        <title>Portal Smartcity Bali</title>
        {/* Required meta tags */}
        <meta charSet="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        {/* Bootstrap CSS */}
        <link rel="stylesheet" href="css/bootstrap.min.css" />
        {/* Animate CSS */}
        <link rel="stylesheet" href="css/animate.min.css" />
        {/* Meanmenu CSS */}
        <link rel="stylesheet" href="css/meanmenu.css" />
        {/* Boxicons CSS */}
        <link rel="stylesheet" href="css/boxicons.min.css" />
        {/* Owl Carousel CSS */}
        <link rel="stylesheet" href="css/owl.carousel.min.css" />
        {/* Owl Carousel Default CSS */}
        <link rel="stylesheet" href="css/owl.theme.default.min.css" />
        {/* Magnific Popup CSS */}
        {/* <link rel="stylesheet" href="css/magnific-popup.min.css" /> */}
        {/* Nice Select CSS */}
        <link rel="stylesheet" href="css/nice-select.min.css" />
        {/* Style CSS */}
        <link rel="stylesheet" href="css/style.css" />
        {/* Dark CSS */}
        <link rel="stylesheet" href="css/dark.css" />
        {/* Responsive CSS */}
        <link rel="stylesheet" href="css/responsive.css" />
        <title>Portal Smart City Bali</title>
        <link rel="icon" type="image/png" href="img/icon-jepun.png" /><meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/algorskorl.png" />
      </Head>
    <Navbar ></Navbar>
    <Konten></Konten>
    
    <Script src="js/jquery.min.js"></Script>
    <Script src="js/popper.min.js"></Script>
    <Script src="js/bootstrap.min.js"></Script>
    <Script src="js/jquery.meanmenu.js"></Script>
    <Script src="js/owl.carousel.min.js"></Script>
    <Script src="js/jquery.magnific-popup.min.js"></Script>
    <Script src="js/nice-select.min.js"></Script>
    <Script src="js/jquery.ajaxchimp.min.js"></Script>
    <Script src="js/form-validator.min.js"></Script>
    {/* <Script src="js/contact-form-script.js"></Script> */}
    <Script src="js/wow.min.js"></Script>
    <Script src="js/main.js"></Script>

    </div>
  )
}

