import React from 'react'
import Head from 'next/head'
import Navbar from './Navbar'
import Footer from './Footer'
// import Konten from './Konten'
// import { useRouter } from "next/router";

export default function BaseLayouts(props) {
  return (
    <div className="first:w-full min-h-screen flex flex-row">
      <Head>
        <title>Portal Smartcity Bali</title>
        {/* Required meta tags */}
        <meta charSet="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
    

        <title>Portal Smart City Bali</title>
        <link rel="icon" type="image/png" href="/img/icon-jepun.png" /><meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/icon-jepun.png" />
      </Head>
    <Navbar>
      {props.children}
    </Navbar>

    <Footer>
      
    </Footer>
    
    {/* <Konten></Konten> */}

    {/* <Script src="js/jquery.min.js"></Script>
    <Script src="js/popper.min.js"></Script>
    <Script src="js/bootstrap.min.js"></Script>
    <Script src="js/jquery.meanmenu.js"></Script>
    <Script src="js/owl.carousel.min.js"></Script>
    <Script src="js/jquery.magnific-popup.min.js"></Script>
    <Script src="js/nice-select.min.js"></Script>
    <Script src="js/jquery.ajaxchimp.min.js"></Script>
    <Script src="js/form-validator.min.js"></Script> */}
    {/* <Script src="js/contact-form-script.js"></Script> */}
    {/* <Script src="js/wow.min.js"></Script>
    <Script src="js/main.js"></Script> */}      

    </div>
  )
}

