import React from 'react'
import Image from 'next/image'
import Head from 'next/head'
// import Footer from './Footer'
import {
    MDBBtn,
    MDBContainer,
    MDBCard,
    MDBCardBody,
    MDBCardImage,
    MDBRow,
    MDBCol,
    MDBIcon,
    MDBInput
  }
  from 'mdb-react-ui-kit';

export default function Login() {
  return (
    <>
    <Head>
    <title>Form Login</title>
        {/* Required meta tags */}
        <meta charSet="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        
        <title>Portal Smart City Bali - Form Login</title>
        <link rel="icon" type="image/png" href="/images/icon-jepun.png" /><meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/icon-jepun.png" />
    </Head>
    <section id="main">
        <video src="/images/video.mp4" muted autoPlay loop></video>
        <MDBContainer fluid>
        <MDBRow className='d-flex justify-content-center align-items-center h-100'>
            <MDBCol col='12'>

            <MDBCard className='bg-dark text-white my-5 mx-auto' style={{borderRadius: '1rem', maxWidth: '400px'}}>
                <MDBCardBody className='p-5 d-flex flex-column align-items-center mx-auto w-100'>
                <Image className="mb-4" src="/images/logo2.png" width={90} height={90} alt="" />
                <h2 className="fw-bold mb-2 text-2xl text-white">Form Login</h2>
                <p className="text-white-50 mb-5">Please enter your login and password!</p>

                <MDBInput wrapperClass='mb-4 mx-5 w-100' labelClass='text-white' label='Email address' id='formControlLg' type='email' size="lg"/>
                <MDBInput wrapperClass='mb-4 mx-5 w-100' labelClass='text-white' label='Password' id='formControlLg' type='password' size="lg"/>

                <p className="small mb-3 pb-lg-2"><a class="text-white-50" href="#!">Forgot password?</a></p>
                <MDBBtn outline className='mx-2 px-5' color='white' size='lg'>
                    Login
                </MDBBtn>

                <div className='d-flex flex-row mt-3 mb-5'>
                    <MDBBtn tag='a' color='none' className='m-3' style={{ color: 'white' }}>
                    <MDBIcon fab icon='facebook-f' size="lg"/>
                    </MDBBtn>

                    <MDBBtn tag='a' color='none' className='m-3' style={{ color: 'white' }}>
                    <MDBIcon fab icon='twitter' size="lg"/>
                    </MDBBtn>

                    <MDBBtn tag='a' color='none' className='m-3' style={{ color: 'white' }}>
                    <MDBIcon fab icon='google' size="lg"/>
                    </MDBBtn>
                </div>

                <div>
                    <p className="mb-0">Dont have an account? <a href="#!" class="text-white-50 fw-bold">Sign Up</a></p>

                </div>
                </MDBCardBody>
            </MDBCard>

            </MDBCol>
        </MDBRow>

        </MDBContainer>
        {/* <Footer>
            
        </Footer> */}
    </section>
    </>
  )
}
